name: build

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - 'src/**'
      - '.github/**'
      - 'pom.xml'


jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
